name: '"Configure Namespace Cloud" Action For GitHub Actions'
description: "Configure a Namespace Cloud cluster and expose a preconfigured kubectl to access it"
runs:
  using: "node16"
  main: "lib/main.js"
