name: e2e
on: [push]

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  run_nscloud_action:
    runs-on: ubuntu-latest
    name: Deploy a sample application to Namespace Cloud
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create Cluster
        uses: ./ # Uses an action in the root directory
      - name: Apply configurations
        run: |
          kubectl apply -f testdata/kubernetes/demo.yaml
      - name: Sleep for 10 seconds
        run: sleep 10s
        shell: bash
      - name: Check result
        run: |
          kubectl -n demo-app get all
