name: e2e
on: [push]

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  run_nscloud_action:
    runs-on: ubuntu-latest
    name: Deploy a sample application to Namespace Cloud
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: namespacelabs/nscloud-setup@v0.0.1
      - name: Create Cluster
        uses: ./ # Uses an action in the root directory
      - name: Apply configurations
        run: |
          kubectl apply -f testdata/kubernetes/demo.yaml
      - name: Wait until Redis is available
        run: |
          kubectl rollout status -n demo-app --watch --timeout=90s statefulset/demo-redis-server
      - name: Describe Pod
        if: always()
        run: |
          kubectl -n demo-app describe pod
      - name: Check Events
        if: always()
        run: |
          kubectl -n demo-app get events
