name: e2e
on: [push]

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  run_nscloud_action:
    runs-on: ubuntu-latest
    name: Deploy a sample application to Namespace Cloud
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create Cluster
        id: nscloud
        uses: ./ # Uses an action in the root directory
      - name: Output registry
        run: |
          echo "${{ steps.nscloud.outputs.registry-address }}"
      - name: Apply configurations
        run: |
          kubectl apply -f testdata/kubernetes/demo.yaml
      - name: Wait until Redis is available
        run: |
          kubectl rollout status -n demo-app --watch --timeout=180s statefulset/demo-redis-server
      - name: Check result
        run: |
          kubectl get all -A
